export const INPUT_ACTIONS = {
  INTERACT: 'interact',
  SHOOT: 'shoot',
  TOGGLE_PAUSE: 'toggle-pause',
  TOGGLE_INVENTORY: 'toggle-inventory',
  TOGGLE_QUEST_LOG: 'toggle-quest-log',
  USE_SLOT: 'use-slot',
};

export const KEYBOARD_ACTIONS = [
  INPUT_ACTIONS.INTERACT,
  INPUT_ACTIONS.SHOOT,
  INPUT_ACTIONS.TOGGLE_PAUSE,
  INPUT_ACTIONS.TOGGLE_INVENTORY,
  INPUT_ACTIONS.TOGGLE_QUEST_LOG,
  INPUT_ACTIONS.USE_SLOT,
];

export const GAMEPAD_ACTIONS = [
  INPUT_ACTIONS.INTERACT,
  INPUT_ACTIONS.SHOOT,
  INPUT_ACTIONS.TOGGLE_PAUSE,
  INPUT_ACTIONS.TOGGLE_INVENTORY,
  INPUT_ACTIONS.TOGGLE_QUEST_LOG,
];
